file_format: "1"
id: keiler
name: Keiler
type: shield
url: https://github.com/jonathanforking/Keiler
requires: 
  - pro_micro
  - seeeduino_xiao_ble
features:
  - keys
siblings:
  - Keiler_left
  - Keiler_right
  - Keiler_dongle
